POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "John",
    "apellidos": "Wayne",
    "sexo": "F",
    "nombre_usuario": "JoWa",
    "email": "john@mail.com",
    "password": "12345",
    "locacion": "Calle bla, 25, 28005 Madrid",
    "fecha_nacimiento": "1990/12/12",
    "experiencia": "si",
    "imagen": "https://www.guidedogs.org/wp-content/uploads/2019/11/website-donate-mobile.jpg", 
    "descripcion": "ljwhfvjhebrfi"
}

###

POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "john@mail.com",
    "password": "12345"
}





###

GET http://localhost:3000/api/usuarios


###
PUT http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "idUsuario": 1,
    "nombre": "Diego",
    "apellidos": "Valdez",
    "sexo": "M",
    "nombre_usuario": "DieVal", 
    "email": "diego@mail.com", 
    "password": "12345", 
    "locacion": "Calle Grande, 6, 28005 Madrid",
    "fecha_nacimiento": "1980/02/08", 
    "experiencia": "si", 
    "rol": "alquilador",
    "imagen": "https://www.guidedogs.org/wp-content/uploads/2019/11/website-donate-mobile.jpg", 
    "descripcion": "asdasdasdasd"
}


###
DELETE http://localhost:3000/api/usuarios/2


###

GET http://localhost:3000/api/parcelas


###

GET http://localhost:3000/api/parcelas/precioAsc


###

GET http://localhost:3000/api/parcelas/precioDesc

###

GET http://localhost:3000/api/parcelas/tamanoDesc

###


POST http://localhost:3000/api/parcelas
Content-Type: application/json

{
    "titulo": "Parcelita bonita",
    "localizacion": "Calle Pez, 43",
    "tamano_total": 400,
    "tamano_disponible": 20,
    "precio_metro": 12,
    "descripcion": "´kejfòkejr",
    "images": "https://i.avoz.es/default/2018/01/26/00121516980001614100405/Foto/BE27C3F1_1.jpg"
}


###
PUT http://localhost:3000/api/parcelas
Content-Type: application/json

{
    "idParcela": 8,
    "titulo": "PARCELÓN!",
    "localizacion": "Calle Yisucristo, 33",
    "tamano_total": 300,
    "tamano_disponible": 100,
    "precio_metro": 13,
    "descripcion": "kwjefnvkonenfv",
    "images": "https://static.spainhouses.net/fotos/86696582/86696582_3740359_foto_846900.jpg"
}


###
DELETE http://localhost:3000/api/parcelas/10